; Config/DefaultGameplayTags.ini (코어 시스템 태그)

[/Script/GameplayTags.GameplayTagsList]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
FastReplication=True
; ----- 1. 입력 태그 (EnhancedInput과 1:1 매칭) -----
+GameplayTagList=(Tag="Input.Fire", DevComment="발사")
+GameplayTagList=(Tag="Input.Reload", DevComment="재장전")
+GameplayTagList=(Tag="Input.Aim", DevComment="조준")
+GameplayTagList=(Tag="Input.Sprint", DevComment="달리기")
+GameplayTagList=(Tag="Input.Dodge", DevComment="구르기/회피")
+GameplayTagList=(Tag="Input.Interact", DevComment="상호작용")
+GameplayTagList=(Tag="Input.Reload", DevComment="재장전")
+GameplayTagList=(Tag="Input.Skill1", DevComment="스킬 1")
+GameplayTagList=(Tag="Input.Skill2", DevComment="스킬 2")
+GameplayTagList=(Tag="Input.Skill3", DevComment="스킬 3")
+GameplayTagList=(Tag="Input.Skill3", DevComment="스킬 3")

; ----- 2. 상태 태그 (캐릭터의 현재 상태, 중첩 불가) -----
+GameplayTagList=(Tag="State.Movement.Walking", DevComment="걷는 중")
+GameplayTagList=(Tag="State.Movement.Sprinting", DevComment="달리는 중")
+GameplayTagList=(Tag="State.Movement.Rolling", DevComment="구르는 중")

+GameplayTagList=(Tag="State.Action.Firing", DevComment="발사 중")
+GameplayTagList=(Tag="State.Action.Reloading", DevComment="재장전 중")
+GameplayTagList=(Tag="State.Action.Aiming", DevComment="조준 중")
+GameplayTagList=(Tag="State.Action.Casting", DevComment="시전 중")
+GameplayTagList=(Tag="State.Action.Interacting", DevComment="상호작용 중")

+GameplayTagList=(Tag="State.Stamina.Regenerating", DevComment="스테미나가 회복중")

; 중첩 가능 상태
+GameplayTagList=(Tag="State.Condition.Heist", DevComment="탄약 고갈 상태")
+GameplayTagList=(Tag="State.Condition.OverHeating", DevComment="탄약 고갈 상태")

+GameplayTagList=(Tag="State.Condition.DrainAmmo", DevComment="탄약 고갈 상태")
+GameplayTagList=(Tag="State.Condition.Pain", DevComment="고통 상태")
+GameplayTagList=(Tag="State.Condition.Invisible", DevComment="투명 상태")
+GameplayTagList=(Tag="State.Condition.Dead", DevComment="사망 상태")
+GameplayTagList=(Tag="State.Condition.Breathing", DevComment="숨고르기 상태(스테미나 리젠 차단)")

+GameplayTagList=(Tag="State.Immune.Damage", DevComment="무적 (구르기)")

; ----- 3. 쿨다운 태그 (GE가 적용될 때 부여됨) -----
+GameplayTagList=(Tag="Cooldown.Dodge", DevComment="회피 쿨다운")
+GameplayTagList=(Tag="Cooldown.Skill.Heist", DevComment="가속 스킬 쿨다운")
+GameplayTagList=(Tag="Cooldown.Skill.OverHeating", DevComment="과열 스킬 쿨다운")
+GameplayTagList=(Tag="Cooldown.Skill.Repair", DevComment="수리 스킬 쿨다운")
+GameplayTagList=(Tag="Cooldown.Skill.Shockwave", DevComment="충격파 스킬 쿨다운")

; ----- 4. 어빌리티 태그 (어빌리티 자체의 속성) -----
+GameplayTagList=(Tag="Ability.IsAttack", DevComment="공격 판정 어빌리티")
+GameplayTagList=(Tag="Ability.IsAming", DevComment="조준 어빌리티")
+GameplayTagList=(Tag="Ability.IsSprint", DevComment="질주 어빌리티")
+GameplayTagList=(Tag="Ability.IsRoll", DevComment="구르기 어빌리티")
+GameplayTagList=(Tag="Ability.IsSkill", DevComment="스킬 어빌리티")
+GameplayTagList=(Tag="Ability.IsReload", DevComment="재장전 어빌리티")
+GameplayTagList=(Tag="Ability.IsInteract", DevComment="상호작용 어빌리티")
+GameplayTagList=(Tag="Ability.IsSkill.Heist", DevComment="은신 어빌리티")
+GameplayTagList=(Tag="Ability.IsSkill.OverHeating", DevComment="과열 어빌리티")
+GameplayTagList=(Tag="Ability.IsSkill.Repair", DevComment="수리 어빌리티")
+GameplayTagList=(Tag="Ability.IsSkill.Shockwave", DevComment="충격파 어빌리티")

; ----- 4.5. 게임플레이 큐 관련 태그 (FX)
+GameplayTagList=(Tag="GameplayCue.Action.Fire",DevComment="발사 시 효과")

; ----- 5. 데이터 태그 (SetByCaller용 마커) -----
+GameplayTagList=(Tag="Data.Cooldown.Roll", DevComment="쿨다운 시간 전달용")
+GameplayTagList=(Tag="Data.Cooldown.Fire", DevComment="쿨다운 시간 전달용")
+GameplayTagList=(Tag="Data.Cooldown.Skill1", DevComment="쿨다운 시간 전달용")
+GameplayTagList=(Tag="Data.Cooldown.Skill2", DevComment="쿨다운 시간 전달용")
+GameplayTagList=(Tag="Data.Cooldown.Skill3", DevComment="쿨다운 시간 전달용")

+GameplayTagList=(Tag="Data.Cost", DevComment="코스트 값 전달용")
+GameplayTagList=(Tag="Data.Damage", DevComment="데미지 값 전달용")

; ----- 6. 인레이드 관련 페이즈 태그 (게임모드 및 모듈 상태 관리에 사용) -----
+GameplayTagList=(Tag="Game.Phase.Loading", DevComment="로딩 페이즈")
+GameplayTagList=(Tag="Game.Phase.InGame", DevComment="게임 시작됨")

; ----- 7. 기본 액터 및 대상 태그
; [예시입니다]
+GameplayTagList=(Tag="Char.Enemy.Zombie.Sneakers", DevComment="일반 좀비")
+GameplayTagList=(Tag="Char.Enemy.Zombie.Gunner", DevComment="일반 좀비")
+GameplayTagList=(Tag="Char.Enemy.Zombie.Fighter", DevComment="일반 좀비")

; ----- 7. 퀘스트 태그 -----
; [퀘스트 채널]
+GameplayTagList=(Tag="Quest.Event.Interact", DevComment="상호작용 퀘스트 목표 채널")
+GameplayTagList=(Tag="Quest.Event.Kill", DevComment="처치 퀘스트 목표 채널")
+GameplayTagList=(Tag="Quest.Event.Location", DevComment="이동 퀘스트 채널")

; [목표 대상]
+GameplayTagList=(Tag="Quest.Target.FirstBox", DevComment="상호작용 첫 퀘스트 대상")
+GameplayTagList=(Tag="Quest.Target.FirstLocation", DevComment="이동 첫 퀘스트 대상")

; [퀘스트 ID]
+GameplayTagList=(Tag="Quest.ID.Tutorial.01_Move", DevComment="테스트 퀘스트 태그")
+GameplayTagList=(Tag="Quest.ID.Tutorial.02_Interact", DevComment="테스트 퀘스트 태그")
+GameplayTagList=(Tag="Quest.ID.Tutorial.03_Kill", DevComment="테스트 퀘스트 태그")
+GameplayTagList=(Tag="Quest.ID.Main.Act1.01_GetItem", DevComment="테스트 퀘스트 태그")

; [목표 ID]
+GameplayTagList=(Tag="Quest.Obj.Common.Kill", DevComment="단순 처치 목표용")
+GameplayTagList=(Tag="Quest.Obj.Common.Location", DevComment="단순 이동 목표용")
+GameplayTagList=(Tag="Quest.Obj.Common.Interact", DevComment="단순 상호작용 목표용")

